spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver



receiptFile:
  in: src/main/resources/in.txt
  out: src/main/resources/out.txt